apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello
  name: hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - image: bob2606/hello-http:0.8.33
        name: hello-http
        env:
          - name: PORT
            value: "80"
        volumeMounts:
          - name: status
            mountPath: /var/lib/hello-http/status
            readOnly: true

      volumes:
        - name: status
          hostPath:
            path: /home/stagiaire/data/status
            type: File
