apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: www
  name: www
spec:
  replicas: 2
  selector:
    matchLabels:
      app: www
  template:
    metadata:
      labels:
        app: www
    spec:
      containers:
      - image: nginx:1.28
        name: nginx
        ports:
          - name: http
            containerPort: 80
        volumeMounts:
          - name: site
            mountPath: /usr/share/nginx/html
            readOnly: true
            subPath: html
          - name: nginx-conf
            mountPath: /etc/nginx/conf.d
      - image: php:8.2-fpm
        name: php
        volumeMounts:
          - name: site
            mountPath: /var/www/html
            readOnly: false
            subPath: html

      volumes:
        - name: site
          hostPath:
            path: /home/stagiaire/data
            type: Directory

        - name: nginx-conf
          configMap:
            name: nginx-conf

        - name: data
          nfs:
            server: 192.168.56.200
            path: /
