apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: www
  name: www
spec:
  replicas: 2
  selector:
    matchLabels:
      app: www
  template:
    metadata:
      labels:
        app: www
    spec:
      containers:
      - image: nginx:1.28
        name: nginx
        ports:
          - name: http
            containerPort: 80
        volumeMounts:
          - name: html
            mountPath: /usr/share/nginx/html
            readOnly: true
      - image: php:8.2-fpm
        name: php
        volumeMounts:
          - name: html
            mountPath: /var/www/html
            readOnly: false

      volumes:
        - name: html
          hostPath:
            path: /home/stagiaire/data/html
            type: Directory

        - name: data
          nfs:
            server: 192.168.56.200
            path: /
