apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: www
  name: www
spec:
  replicas: 1
  selector:
    matchLabels:
      app: www
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: www
    spec:
      containers:
      - image: nginx:1.28
        name: nginx
        resources: {}
        ports:
          - name: http
            containerPort: 80
      - image: php:8.2-fpm
        name: php
        resources: {}
status: {}
