apiVersion: v1
kind: Pod
metadata:
  labels:
    run: hello
  name: hello
spec:
  containers:
  - image: bob2606/hello-http:0.8.33
    name: hello
  - image: busybox:1.28
    name: busy
    args:
      - tail
      - -f
      - /dev/null
  dnsPolicy: ClusterFirst
  restartPolicy: Always
