apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  labels:
    app: www
  name: www
spec:
  selector:
    matchLabels:
      app: www
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: www
    spec:
      containers:
      - image: nginx:1.28
        name: nginx
        resources: {}
      - image: php:8.2-fpm
        name: php
        resources: {}
status: {}
